name: Validate Gradle Wrapper
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      
