name: Pre Merge Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  gradle:
    runs-on: ubuntu-latest
    env:
      GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
      GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Cache Gradle Caches
        uses: gradle/actions/setup-gradle@v4
      - name: Run Gradle tasks
        run: ./gradlew preMerge --continue

        # We do a run of the new task `templateExample` created by the plugin
      - name: Run the plugin
        run: ./gradlew templateExample --message="Test Run" --tag=CI
        if: success()
        # And we verify that the output of the file is correct.
      - name: Verify the plugin output
        run: grep -Fxq "[CI] Test Run" ./example/build/template-example.txt
        if: success()
